name: Build and Release qlock

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest

    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust targets
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Build (release for ${{ matrix.target }})
        run: cargo build --release --target=${{ matrix.target }}

      - name: Package macOS artifact for ${{ matrix.target }}
        run: |
          mkdir -p dist
          BIN=qlock-${{ matrix.target }}
          cp target/${{ matrix.target }}/release/qlock dist/${BIN}
          tar -C dist -czf dist/${BIN}.tar.gz ${BIN}

      - name: Upload Intel artifact
        if: matrix.target == 'x86_64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: qlock-darwin-x86_64
          path: dist/qlock-x86_64-apple-darwin.tar.gz

      - name: Upload ARM artifact
        if: matrix.target == 'aarch64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: qlock-darwin-arm
          path: dist/qlock-aarch64-apple-darwin.tar.gz

  upload:
    name: Publish Release Assets
    needs: build-macos
    runs-on: ubuntu-latest

    steps:
      - name: Download Intel artifact
        uses: actions/download-artifact@v4
        with:
          name: qlock-darwin-x86_64
          path: dist

      - name: Download ARM artifact
        uses: actions/download-artifact@v4
        with:
          name: qlock-darwin-arm
          path: dist

      - name: Create / Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
